### ISSUE TITLE
typo mother tong -> mother tongue

### ISSUE THREAD

**Issue by gizmomogwai** [Nicoretti/nicoretti.github.io#1]
https://www.google.com/search?q=tong&oq=tong&aqs=chrome..69i57.483j0j7&sourceid=chrome&ie=UTF-8#dobs=mother%20tongue

**Comment by Nicoretti** [comment]
Hi @gizmomogwai,

Happy new year and thanks for catching that one ;).

best
Nico

**Comment by gizmomogwai** [comment]
Happy new year to you too
